# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('balance', models.FloatField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('picture', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_time', models.TimeField()),
                ('create_time', models.DateTimeField()),
                ('accept_time', models.DateTimeField()),
                ('delivery_start_time', models.DateTimeField()),
                ('confirm_delivery_time', models.DateTimeField()),
                ('destination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Courier')),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ET.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('food_id', models.ManyToManyField(to='ET.Food')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('ordertime', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Customer')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.GroupOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('state', models.SlugField(max_length=3)),
                ('address', models.TextField()),
                ('logo', models.URLField()),
                ('money', models.FloatField()),
                ('id_photo', models.URLField()),
                ('business_license', models.URLField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderfood',
            name='personal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.PersonalOrder'),
        ),
        migrations.AddField(
            model_name='group',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='favoriterestaurant',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='courier',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
    ]
