# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_time', models.TimeField()),
                ('create_time', models.DateTimeField()),
                ('accept_time', models.DateTimeField()),
                ('delivery_start_time', models.DateTimeField()),
                ('confirm_delivery_time', models.DateTimeField()),
                ('destination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Courier')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ET.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('money', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('order_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.GroupOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.spatial.LocationField(srid=4326)),
                ('logo', models.ImageField(upload_to='')),
                ('id_number', models.CharField(max_length=50)),
                ('id_photo', models.ImageField(upload_to='')),
                ('business_license', models.ImageField(upload_to='')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ET.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_delivery', models.FloatField(default=0)),
                ('delivery_fee', models.FloatField(default=0)),
                ('announcement', models.TextField(max_length=500)),
                ('service_status', models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='C', max_length=1)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='orderfood',
            name='personal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.PersonalOrder'),
        ),
        migrations.AddField(
            model_name='group',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favourite_restaurants',
            field=models.ManyToManyField(blank=True, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courier',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant'),
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
