# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='courier_login_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='grouporder',
            old_name='courier_id',
            new_name='courier',
        ),
        migrations.RenameField(
            model_name='grouporder',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='orderfood',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='personalorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='personalorder',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='personalorder',
            old_name='ordertime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='favourite_restaurants',
            field=models.ManyToManyField(blank=True, to='ET.Restaurant'),
        ),
        migrations.DeleteModel(
            name='FavoriteRestaurant',
        ),
    ]
