# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_delivery', models.FloatField(default=0)),
                ('delivery_fee', models.FloatField(default=0)),
                ('announcement', models.TextField(max_length=500)),
                ('service_status', models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='C', max_length=1)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ET.Restaurant')),
            ],
        ),
    ]
