# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0002_restaurantserviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
