# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0002_auto_20161024_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
