# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0003_auto_20161024_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Accepted'), ('D', 'Delivering'), ('F', 'Finished')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='personalorder',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('D', 'Delivering'), ('F', 'Finished')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ET.Courier'),
        ),
    ]
