# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0003_auto_20161012_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfood',
            name='food',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ET.Food'),
            preserve_default=False,
        ),
    ]
