# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0003_auto_20161024_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalorder',
            name='delivery_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
