# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0004_auto_20161024_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='available_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='frozen_balance',
            field=models.FloatField(default=0),
        ),
    ]
