# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0004_auto_20161012_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=location_field.models.spatial.LocationField(default=0, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('G', 'Grouping'), ('O', 'Over')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='destination',
            field=models.CharField(max_length=255),
        ),
    ]
