# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0005_auto_20161025_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalorder',
            old_name='group',
            new_name='group_order',
        ),
    ]
