# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0005_auto_20161019_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='accept_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='confirm_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='delivery_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
