# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0005_auto_20161009_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
