# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0006_auto_20161019_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_time',
            field=models.DurationField(),
        ),
    ]
