# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0006_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='contact_name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_number',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
