# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0006_auto_20161025_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalorder',
            name='group_order',
        ),
        migrations.AddField(
            model_name='personalorder',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ET.Group'),
            preserve_default=False,
        ),
    ]
