# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 14:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0007_auto_20161009_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
            preserve_default=False,
        ),
    ]
