# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0007_auto_20161025_1848'),
        ('ET', '0004_auto_20161025_1923'),
    ]

    operations = [
    ]
