# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0008_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.SlugField(choices=[('VIC', 'Victoria '), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('NT', 'The Northern Territory'), ('TAS', 'Tasmania'), ('ACT', 'The Australian Capital Territory')], max_length=3),
        ),
    ]
