# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0009_auto_20161011_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
    ]
