# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0009_auto_20161025_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='price_delivery',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='price_food',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='price_total',
            field=models.FloatField(default=0),
        ),
    ]
