# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0012_auto_20161025_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantserviceinfo',
            name='delivery_fee',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='restaurantserviceinfo',
            name='min_delivery',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
