# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0013_auto_20161026_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantserviceinfo',
            name='announcement',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
