# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0014_auto_20161026_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalorder',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('S', 'Submitted'), ('D', 'Delivering'), ('F', 'Delivered'), ('U', 'Undelivered')], default='W', max_length=1),
        ),
    ]
